
DROP TABLE T_SIP_DEPENDENTE CASCADE CONSTRAINTS; -- OPÇÃO CASCADE CONSTRAINTS ELIMINA O RELACIONAMENTO 

DROP TABLE T_SIP_IMPLANTACAO CASCADE CONSTRAINTS; 

DROP TABLE T_SIP_PROJETO        CASCADE CONSTRAINTS; 

DROP TABLE T_SIP_FUNCIONARIO    CASCADE CONSTRAINTS; 

DROP TABLE T_SIP_DEPTO CASCADE CONSTRAINTS; 



CREATE TABLE T_SIP_DEPTO 
( 

CD_DEPTO NUMBER(3) NOT NULL , 

NM_DEPTO VARCHAR2(40) NOT NULL , 

SG_DEPTO        CHAR(3) NOT NULL 

); 

   

   ALTER TABLE T_SIP_DEPTO   

ADD CONSTRAINT PK_SIP_DEPTO  

   PRIMARY KEY (CD_DEPTO);   

 

   ALTER TABLE T_SIP_DEPTO 

ADD CONSTRAINT UN_SIP_DEPTO_NOME 

        UNIQUE (NM_DEPTO);      


CREATE TABLE T_SIP_FUNCIONARIO 

( 

NR_MATRICULA NUMBER(5) NOT NULL , 

CD_DEPTO NUMBER(3) NOT NULL , 

NM_FUNCIONARIO VARCHAR2(60) NOT NULL , 

DT_NASCIMENTO DATE NOT NULL , 

DT_ADMISSAO DATE NOT NULL , 

DS_ENDERECO VARCHAR2(100) NOT NULL , 

VL_SALARIO NUMBER(7,2) NOT NULL 

); 

  


   ALTER TABLE T_SIP_FUNCIONARIO 

ADD CONSTRAINT PK_SIP_FUNCIONARIO 

   PRIMARY KEY (NR_MATRICULA); 

  


   ALTER TABLE T_SIP_FUNCIONARIO 

ADD CONSTRAINT CK_SIP_FUNC_SALARIO 

         CHECK (VL_SALARIO >= 1045); 

  
CREATE TABLE T_SIP_DEPENDENTE 

( 

NR_MATRICULA NUMBER(5) NOT NULL , 

CD_DEPENDENTE NUMBER(2) NOT NULL , 

NM_DEPENDENTE VARCHAR2(60) NOT NULL , 

DT_NASCIMENTO DATE NOT NULL 

); 


   ALTER TABLE T_SIP_DEPENDENTE 

ADD CONSTRAINT PK_SIP_DEPENDENTE 

   PRIMARY KEY (NR_MATRICULA,CD_DEPENDENTE);


CREATE TABLE T_SIP_PROJETO 

( 

    CD_PROJETO       NUMBER (5)      NOT NULL , 

    NM_PROJETO       VARCHAR2(40)    NOT NULL , 

    DT_INICIO        DATE            NOT NULL , 

    DT_TERMINO       DATE                NULL  

); 


    ALTER TABLE T_SIP_PROJETO  

ADD CONSTRAINT PK_SIP_PROJETO 

    PRIMARY KEY (CD_PROJETO);  


    ALTER TABLE T_SIP_PROJETO    

ADD CONSTRAINT UN_SIP_PROJETO_NOME  

         UNIQUE (NM_PROJETO); 


    ALTER TABLE T_SIP_PROJETO 

ADD CONSTRAINT CK_SIP_PROJETO_DATA 

          CHECK (DT_TERMINO > DT_INICIO);    

  

CREATE TABLE T_SIP_IMPLANTACAO 
( 

CD_PROJETO NUMBER(5) NOT NULL , 

CD_IMPLANTACAO NUMBER(3) NOT NULL , 

NR_MATRICULA NUMBER(5) NOT NULL , 

DT_ENTRADA DATE NOT NULL , 

DT_SAIDA DATE     NULL 

); 



  ALTER  TABLE T_SIP_IMPLANTACAO 

ADD CONSTRAINT PK_SIP_IMPLANTACAO 

   PRIMARY KEY (CD_PROJETO,CD_IMPLANTACAO); 


   ALTER TABLE T_SIP_IMPLANTACAO 

ADD CONSTRAINT CK_SIP_IMPLANT_DATA 

         CHECK (DT_SAIDA > DT_ENTRADA); 



   ALTER TABLE T_SIP_FUNCIONARIO 

ADD CONSTRAINT FK_SIP_FUNC_DEPTO 

   FOREIGN KEY (CD_DEPTO)        

    REFERENCES T_SIP_DEPTO       

           (CD_DEPTO);       


   ALTER TABLE T_SIP_DEPENDENTE 

ADD CONSTRAINT FK_SIP_DEPENDENTE_FUNC 

   FOREIGN KEY (NR_MATRICULA) 

    REFERENCES T_SIP_FUNCIONARIO (NR_MATRICULA); 


    ALTER TABLE T_SIP_IMPLANTACAO  

ADD CONSTRAINT FK_SIP_IMPLANT_PROJETO  

    FOREIGN KEY (CD_PROJETO)         

     REFERENCES T_SIP_PROJETO (CD_PROJETO);   


   alter table T_SIP_IMPLANTACAO 

add constraint FK_SIP_IMPLANT_FUNC 

   foreign key (NR_MATRICULA) 

    references T_SIP_FUNCIONARIO (NR_MATRICULA); 